export const config = {
  port: parseInt(process.env.PORT, 10) || 3001,
  storageMode: process.env.STORAGE_MODE || 'physical',
  vibesqlUrl: process.env.VIBESQL_URL || 'http://10.0.0.93:5173',
  vibeApiUrl: process.env.VIBE_API_URL || 'http://10.0.0.93:32786',
  vibeClientId: parseInt(process.env.VIBE_CLIENT_ID, 10) || 1,
  vibeTokenCmd: process.env.VIBE_TOKEN_CMD || './cli.js token',
  vibeTokenRefreshS: parseInt(process.env.VIBE_TOKEN_REFRESH_S, 10) || 300,
  vibeAuthMode: process.env.VIBE_AUTH_MODE || 'bearer',
  vibeSigningKey: process.env.VIBE_SIGNING_KEY || '',
  execTimeoutMs: parseInt(process.env.EXEC_TIMEOUT_MS, 10) || 5000,
  nodeEnv: process.env.NODE_ENV || 'development',
  logLevel: process.env.LOG_LEVEL || 'info',
  acpDataDir: process.env.ACP_DATA_DIR || '.acp',
  corsOrigins: process.env.CORS_ALLOWED_ORIGINS || '*',
  partyTickMs: parseInt(process.env.PARTY_TICK_MS, 10) || 5000,
  autonomyMaxRuntimeHours: parseInt(process.env.AUTONOMY_MAX_RUNTIME_HOURS, 10) || 4,
  escalationSensitivity: parseInt(process.env.ESCALATION_SENSITIVITY, 10) || 2,
};
