#!/usr/bin/env node
/**
 * gen-env — codegen the active-environment endpoint set for the MAIN process (WO #292).
 *
 * The main process is built with `tsc` (not Vite), so a Vite `define` can't bake
 * the env into it. Instead this script reads the explicit `ACP_ENV`, resolves it
 * against scripts/environments.cjs, and writes ONLY the active env's hosts into
 * src/main/env.generated.ts (which tsc then compiles into the main bundle).
 *
 * GUARANTEES (the #292 bar):
 *  - NO default: `ACP_ENV` unset or unknown -> THROW + exit 1 (never default to dev or prod).
 *  - ACTIVE-SET-ONLY: only the chosen env's hosts are written -> a prod build's
 *    generated source contains NO dev literal (immutability by construction).
 *  - AC-9 OVERWRITE-ALWAYS: unconditionally truncates + rewrites every run. NEVER
 *    skip-if-exists — a stale dev93 file compiling into a prod build is the exact
 *    wrong-env-shipped bug #292 exists to kill. The build chain runs this FIRST,
 *    every build, with that build's ACP_ENV.
 *  - The generated file stamps ACP_ENV_NAME so the runtime/build can assert the
 *    baked env matches the one that was requested.
 */
const fs = require('fs');
const path = require('path');
const { ENVIRONMENTS, ENV_NAMES, REQUIRED_KEYS } = require('./environments.cjs');

// The env is chosen explicitly: a CLI arg (cross-platform, used by the npm
// scripts) takes precedence, else the ACP_ENV env var (for CI). NO default.
const env = process.argv[2] || process.env.ACP_ENV;

// NO default — fail loud on unset OR invalid (Jon's no-fallback law).
if (!env) {
  console.error(
    `[gen-env] FATAL: no environment chosen. Pass one explicitly ` +
    `(one of: ${ENV_NAMES.join(', ')}), e.g. \`node scripts/gen-env.cjs prod\`. ` +
    `Use a named script: \`npm run dev:93\` / \`npm run dev:prod\`. ` +
    `Refusing to generate a default-env build.`,
  );
  process.exit(1);
}
if (!ENV_NAMES.includes(env)) {
  console.error(
    `[gen-env] FATAL: ACP_ENV='${env}' is not a known environment ` +
    `(known: ${ENV_NAMES.join(', ')}). Refusing to generate.`,
  );
  process.exit(1);
}

const active = ENVIRONMENTS[env];
const missing = REQUIRED_KEYS.filter((k) => !active[k]);
if (missing.length) {
  console.error(`[gen-env] FATAL: env '${env}' is missing required host(s): ${missing.join(', ')}.`);
  process.exit(1);
}

const outPath = path.join(__dirname, '..', 'src', 'main', 'env.generated.ts');
const banner =
  `// ╔══════════════════════════════════════════════════════════════════════╗\n` +
  `// ║ AUTO-GENERATED by scripts/gen-env.cjs — DO NOT EDIT.                   ║\n` +
  `// ║ Regenerated on EVERY build from the invoked ACP_ENV. Hand edits and   ║\n` +
  `// ║ stale copies are overwritten. This file is gitignored.                ║\n` +
  `// ╚══════════════════════════════════════════════════════════════════════╝\n`;

const body =
  `${banner}` +
  // Typed as `string` (NOT a narrow `as const` literal): a per-build literal
  // would make comparisons like `ACP_ENV_NAME !== 'prod'` a TS2367 "no overlap"
  // error in any build whose baked value differs from the compared literal.
  `export const ACP_ENV_NAME: string = ${JSON.stringify(env)};\n\n` +
  `export interface CloudEnv {\n` +
  `  idpUrl: string;\n` +
  `  idpInternalUrl?: string; // dev-only (/dev/impersonate); absent in prod\n` +
  `  vibeApiUrl: string;\n` +
  `  hubUrl: string;\n` +
  `}\n\n` +
  `// ONLY the '${env}' env's hosts are baked here — no other env's literals exist\n` +
  `// in this build's main bundle.\n` +
  `export const ACP_ENDPOINTS: CloudEnv = ${JSON.stringify(active, null, 2)};\n`;

// AC-9: unconditional overwrite (truncate + write), never skip-if-exists.
fs.writeFileSync(outPath, body, { encoding: 'utf8', flag: 'w' });
console.log(`[gen-env] wrote ${path.relative(path.join(__dirname, '..'), outPath)} for ACP_ENV='${env}'.`);
